### PR TITLE
Create create_coco_dataset.py

### PR DESCRIPTION
**Pull request by GeorgePearse**
I've seen people commenting on @SkalskiP 's youtube tutorial, asking how to create a COCO object detection dataset ready for training. Voxel 51 makes this very easy.

Thought this was a reasonably good place to leave this code snippet even if it just stays as a PR. Happy to tweak in any way if you like the idea.

### CODE REVIEW

**Comment by SlongLiu** [comment]
Thanks! I will merge the PR now.

**Comment by SkalskiP** [comment]
Hi 👋🏻! I’m actually going to release one more video today. Will talk about evacuation of Grounding DINO 🦖 on COCO datasets + auto annotation.

**Comment by SkalskiP** [comment]
Here it is: https://youtu.be/C4NqaRBz_Kw

**Comment by SlongLiu** [comment]
Cool! I will refine the readme to add the new video.

**Comment by SlongLiu** [comment]
Hi, we have built a new repo to [combine the grounding dino with segment anything](https://github.com/IDEA-Research/Grounded-Segment-Anything), which enables to detect and segment everything with language inputs.

**Comment by SkalskiP** [comment]
🔥 @SlongLiu you are the best! When I was thinking about it… you already made it! I wanted to build something over the weekend haha

**Comment by SlongLiu** [comment]
Hahah. great minds think alike. Looking forward to more interesting improvements.

Another notebook to marry grounding dino and stable diffusion is ready as well: https://github.com/IDEA-Research/GroundingDINO/blob/main/demo/image_editing_with_groundingdino_stablediffusion.ipynb .

**Comment by amanikiruga** [comment]
Hey @SkalskiP I've noticed in your code, you delimit the classes with a comma. @SlongLiu can confirm but when I delimit with a period I get higher accuracy and better results. Also, the hugginface demo for segment-anything also delimits with a period. https://huggingface.co/spaces/yizhangliu/Grounded-Segment-Anything

**Comment by SkalskiP** [comment]
Hi @amanikiruga 👋🏻 I’ll do some tests (hopefully) tomorrow and try to confirm that. If you are right I’m happy to apply the changes.

**Pull request merged**
