### PR TITLE
fix Supervision depreciation of BoxAnnotator

### PR DESCRIPTION
**Pull request by ethanlee928**
Saw a warning when calling `annotate`:
```SupervisionWarnings: annotate is deprecated: BoxAnnotator is deprecated and will be removed in supervision-0.22.0. Use BoundingBoxAnnotator and LabelAnnotator instead```

Fixed by removing `BoxAnnotator` and use `BoundingBoxAnnotator` and `LabelAnnotator` as instructed by the warning.
And based on `supervision` [release note](https://supervision.roboflow.com/latest/changelog/#0150-october-5-2023), `BoundingBoxAnnotator` is added in version `0.15.0` .

Please review. Thank you!

### CODE REVIEW

**Review by pg56714 — APPROVED** [review]

**Review by pg56714 — CHANGES_REQUESTED** [review]
@ethanlee928 

It seems there's been some confusion with version updates and the renaming of classes. Based latest information, `BoundingBoxAnnotator` has been renamed to `BoxAnnotator` and will be removed in future versions. Therefore, you should use `BoxAnnotator` instead of `BoundingBoxAnnotator`. Here is the corrected code:

```python
bbox_annotator = sv.BoxAnnotator(color_lookup=sv.ColorLookup.INDEX)
```

With this update, your code will comply with the latest library standards, ensuring backward compatibility.

image


This PR can fix the following error:
```
TypeError: BoxAnnotator.annotate() got an unexpected keyword argument 'labels'
```

Thank you for your PR.

**Comment by ethanlee928** [comment]
> @ethanlee928
> 
> It seems there's been some confusion with version updates and the renaming of classes. Based latest information, `BoundingBoxAnnotator` has been renamed to `BoxAnnotator` and will be removed in future versions. Therefore, you should use `BoxAnnotator` instead of `BoundingBoxAnnotator`. Here is the corrected code:
> 
> ```python
> bbox_annotator = sv.BoxAnnotator(color_lookup=sv.ColorLookup.INDEX)
> ```
> 
> With this update, your code will comply with the latest library standards, ensuring backward compatibility.
> 
> image
> 
> This PR can fix the following error:
> 
> ```
> TypeError: BoxAnnotator.annotate() got an unexpected keyword argument 'labels'
> ```
> 
> Thank you for your PR.

@pg56714 Thanks for providing the latest information, I've updated the PR based on your suggestion.

**Review by pg56714 — APPROVED** [review]

**Comment by ethanlee928** [comment]
@SkalskiP 
Friendly ping to see if you had a chance to look at this PR related to Supervision. Appreciate any feedback when you get a moment. Thanks!

**Review by SkalskiP — APPROVED** [review]

**Comment by SkalskiP** [comment]
Hi @ethanlee928 👋🏻, I did not know this PR existed. Looks good. Thanks a lot for the help in migrating from the old to the new supervision API.

**Pull request merged**
