### PR TITLE
support to use transformer model offline

### PR DESCRIPTION
**Pull request by HaoLiuHust**
For now, when we use GroundingDINO, the program will download bert models from huggingface, sometimes, we want to use it offline.  The "transformers" library supports to input a directory to it, however, some check in our code will raise an error

### CODE REVIEW

**Comment by sophieDataroots** [comment]
Can you explain how you loaded the Bert model offline? I'm trying to do the same

**Comment by HaoLiuHust** [comment]
> Can you explain how you loaded the Bert model offline? I'm trying to do the same

you can download bert models from huggingface at first, put them into a folder, and set param "text_encoder_type" as the folder path.

for detail usage, you can refer to https://github.com/HaoLiuHust/GroundingDINO-Service

**Comment by sophieDataroots** [comment]
Which param do I need to set in which function?

**Comment by HaoLiuHust** [comment]
> Which param do I need to set in which function?
you can set it in config file: 
https://github.com/IDEA-Research/GroundingDINO/blob/main/groundingdino/config/GroundingDINO_SwinT_OGC.py
image

or you can set it befer build model:
args.text_xxx
https://github.com/IDEA-Research/GroundingDINO/blob/main/demo/inference_on_a_image.py
image

**Pull request merged**
